num1 = int(input("Введите первое число: "))
num2 = int(input("Введите второе число: "))
print("\nСумма:", num1+num2)
print("\nВычитание:", num1-num2)
print("\nУмножение", num1*num2)
print("\nДеление:", num1/num2)
print("\nДеление (остаток):", num1%num2)
print("\nДеление (целая часть):", num1//num2)
print("\nВозведение в степень:", num1**num2, "\n")
print()